import { InMemoryDbService } from 'angular-in-memory-web-api';
import { InventoryCategory } from './InventoryCategory';

   export class InventoryCategoryData implements InMemoryDbService {

  createDb() {
    const InventoryCategorys: InventoryCategory[] = [
      {
        id: 1,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 2,
        Alias: 'Leaf Rake1',
        ShortString: 'Leaf Rake1',
        LongString: 'Leaf Rake1',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 1,
      },
      {
        id: 3,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 4,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 5,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 6,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      },
      {
        id: 0,
        Alias: 'Leaf Rake',
        ShortString: 'Leaf Rake',
        LongString: 'Leaf Rake',
        IsDeleted: null,
        CreationDate:null,
        LastEditDate:null,
        InsertUserId:null,
        UpdateUserId:null,
        DeleteUserId:null,
        CanShowDialogForScan: 0,
      }
      

    ];
    return { InventoryCategorys };
  }
}  
